CLASS zrap_disc_event_handler DEFINITION
  PUBLIC
  FINAL FOR EVENTS OF zi_disc_travel
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zrap_disc_event_handler IMPLEMENTATION.
ENDCLASS.
